### ISSUE TITLE
Tradução do dropdown da exibição 10/page 20/page 30/page 

### ISSUE THREAD

**Issue by jessicagsanttos** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#100]
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/81448431/10b1c7e8-ccc4-4073-9e3d-2e46fb6d2a27)

**Comment by ThiagoTerrinha** [comment]
Corrigido.
