### ISSUE TITLE
Bug - Ao utilizar filtro na tela de cadastro do idoso ocorre um erro

### ISSUE THREAD

**Issue by jessicagsanttos** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#101]
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/81448431/b5ec8c95-1ae6-4cb3-a31d-ff96ad5fd27d)

**Comment by ThiagoTerrinha** [comment]
Corrigido.
