### ISSUE TITLE
Marcação de campos obrigatórios com * 

### ISSUE THREAD

**Issue by jessicagsanttos** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#96]
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/81448431/a85e02fd-0fcb-4ef4-ad7c-3b1d3cece494)

Marcar campos obrigatórios com asterisco, mantendo a mesma regra da aba de identificação e replicando para as abas "Documentos" e "responsáveis"

**Comment by ThiagoTerrinha** [comment]
Perfeito, esses campos não estão obrigatório pois seguimos o documentação dos requisitos do cadastro do idoso, e lá solicitava que não fosse obrigatório os campos dos documentos. Poderiam me confirmar se está correto a documentação: 

https://sgapucminasbr-my.sharepoint.com/:w:/r/personal/1401789_sga_pucminas_br/_layouts/15/Doc.aspx?sourcedoc=%7BA5D2799E-9429-41F5-B23D-BB2D8707EA84%7D&file=Requisitos%20Cadastro%20Idoso.docx&action=default&mobileredirect=true
