### ISSUE TITLE
Bug - Responsável pelo idoso não salva ao tentar cadastrar

### ISSUE THREAD

**Issue by jessicagsanttos** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#97]
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/81448431/008621e4-55ae-42a6-9cf7-92a8feaa6bc0)

**bug, ao preencher todos os campos e salvar o cadastro não é salvo **

**Comment by ThiagoTerrinha** [comment]
Corrigido.
