### ISSUE TITLE
bug? O nome do usuário está sendo aceito mesmo com o uso dos caracteres traço - e ponto final .

### ISSUE THREAD

**Issue by euanacarmo** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#98]
<img width="1440" alt="3  com traços e pontos - o sistema autorizou" src="https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/101269435/e1b37bbd-30c5-4f35-94d7-bcf3b3d93d8b">

**Comment by ThiagoTerrinha** [comment]
Corrigido.
