### ISSUE TITLE
bug? Mesmo após a inativação do cargo, ele continua aparecendo

### ISSUE THREAD

**Issue by euanacarmo** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo#99]
<img width="1440" alt="3  o cargo continua aparecendo" src="https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e5-proj-empext-t2-sistema-lar-sao-vicente-de-paulo/assets/101269435/0a9b8ba4-e066-46aa-a0c4-0b09e2bf0f7b">

**Comment by ThiagoTerrinha** [comment]
Corrigido.
